### PR TITLE
docs: Add Inga plugin to README.md

### PR DESCRIPTION
**Pull request by seachicken**
Hi, congratulations on the release of LSP4IJ! I released [my plugin](https://plugins.jetbrains.com/plugin/24358-inga) on the marketplace, so please add me as an LSP4IJ user if you like. This plugin connects LSP4IJ to a local language server in a container. https://github.com/redhat-developer/lsp4ij/discussions/286#discussioncomment-9375571

### CODE REVIEW

**Comment by angelozerr** [comment]
We are glad that LSP4IJ can help you.

Thanks for your contribution!

**Comment by angelozerr** [comment]
@seachicken could you please update your commit by adding docs: because the ci build is failling

**Review by fbricon — APPROVED** [review]

**Comment by fbricon** [comment]
Thanks @seachicken

**Comment by angelozerr** [comment]
@seachicken if you are happy with LSP4IJ could you please help us to promote LSP4IJ with your review at https://plugins.jetbrains.com/plugin/23257-lsp4ij/edit/reviews

Thanks!

**Pull request merged**
